services:
  vr-dev:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: vr-dev
    privileged: true
    devices:
      - "/dev/bus/usb/:/dev/bus/usb"
    device_cgroup_rules:
      - "c 189:* rmw"
    gpus: all
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=${DISPLAY}
    volumes:
      - ../:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/udev/rules.d:/etc/udev/rules.d
    working_dir: /workspace
    network_mode: host
    stdin_open: true
    tty: true
    cap_add:
      - SYS_ADMIN
      - SYS_PTRACE
      - SYS_RAWIO
